version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
  ui:
    build: ./ui
    ports:
      - "3000:80"
    depends_on:
      - backend 