name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxtst-dev libwebsocketpp-dev libboost-all-dev
      - name: Build core (WebRTC disabled for CI)
        run: |
          cd core
          cmake -B build -DUSE_WEBRTC=OFF
          cmake --build build
  backend-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install and check backend
        run: |
          cd backend
          cp package-ci.json package.json
          npm install
          npm run build || true
      - name: Install and check UI
        run: |
          cd ui
          npm install --legacy-peer-deps
          npm run build || true
